name: Tests & Lints
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - name: Get dependencies for main app
        run: flutter pub get
      - name: Analyze main app
        run: flutter analyze
      - name: Get dependencies for `repositories` package
        run: flutter pub get
        working-directory: ./packages/repositories
      - name: Analyze `repositories` package
        run: flutter analyze
        working-directory: ./packages/repositories
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test