name: Flutter action
on: [push]
jobs:
  lint:
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.8'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
  test:
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.8'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test